FROM mcr.microsoft.com/devcontainers/base:bookworm

RUN apt update && apt install -y \
    python3-pip \
    python3-venv \
    python3-dev \
    python3-django \
    python3-psycopg2\
    && apt-get clean